# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=64)),
                ('admin_first_name', models.CharField(max_length=64)),
                ('admin_last_name', models.CharField(max_length=64)),
                ('admin_email', models.CharField(max_length=64)),
                ('admin_password', models.CharField(max_length=64)),
                ('admin_authority', models.CharField(max_length=10)),
                ('admin_create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
