# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_username',
        ),
    ]
