# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20190226_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lower_category',
            old_name='s_name',
            new_name='lower_name',
        ),
        migrations.RenameField(
            model_name='upper_category',
            old_name='b_name',
            new_name='upper_name',
        ),
    ]
