# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_product_info_upper_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='Upper_category',
        ),
        migrations.AddField(
            model_name='product_info',
            name='Upper_code',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
